from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path

from apps.core.views import core_views
from apps.movimentacao.views import movimentacao_views
from apps.relatorio import views as views_rel
from apps.usuario.views import usuario_views

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        core_views.dashboard,
        name="escolha_dashboard",
    ),
    path(
        "installsystem",
        core_views.isntalar_sistema,
        name="install_system",
    ),
    # Relatórios
    path(
        "relatorio/",
        views_rel.relatorio,
        name="relatorio",
    ),
    path(
        "relatorio/solicitacoesdoperfil/",
        views_rel.solicitacoes_pendentes_do_perfil,
        name="rel_solicitacoes_do_perfil",
    ),
    path(
        "relatorio/solicitacoesdosetor/",
        views_rel.solicitacoes_pendentes_do_meu_setor,
        name="rel_solicitacoes_do_setor",
    ),
    # Painel de controle do super administrador
    path(
        "administrador/",
        core_views.administrador,
        name="administrador",
    ),
    path(
        "administrador/setor",
        core_views.setor,
        name="setor",
    ),
    path(
        "administrador/setor/selecionar/<int:id>",
        core_views.administrador_mostra_setor,
        name="administrador_setor_id",
    ),
    path(
        "administrador/setor/deletar/<int:id>",
        core_views.setor_delete,
        name="setor_deletar",
    ),
    path(
        "administrador/setor/atualizar/<int:id>",
        core_views.setor_atualiza,
        name="setor_atualiza",
    ),
    path(
        "administrador/extra",
        core_views.administrador_extra,
        name="administrador_extra",
    ),
    path(
        "administrador/extra/modificarconfiguracao/<int:id>",
        core_views.hash_edit,
        name="hash",
    ),
    path(
        "administrador/status/cadastrar",
        core_views.status,
        name="cadastrar_status",
    ),
    path(
        "administrador/status/padronizar/analise/<int:id>",
        core_views.status_torna_padrao_analise,
        name="status_tornar_padrao_analise",
    ),
    path(
        "administrador/status/padronizar/autorizado/<int:id>",
        core_views.status_torna_padrao_autorizado,
        name="status_tornar_padrao_autorizado",
    ),
    path(
        "administrador/status/editar/<int:id>",
        core_views.status_editar,
        name="status_editar",
    ),
    path(
        "administrador/status/deletar/<int:id>",
        core_views.status_delete,
        name="status_deletar",
    ),
    path(
        "administrador/formadepagamento/cadastrar",
        core_views.forma_de_pagamento,
        name="forma_de_pagamento",
    ),
    path(
        "administrador/formadepagamento/editar/<int:id>",
        core_views.forma_de_pagamento_editar,
        name="forma_de_pagamento_editar",
    ),
    path(
        "administrador/formadepagamento/deletar/<int:id>",
        core_views.forma_de_pagamento_delete,
        name="forma_de_pagamento_deletar",
    ),
    # Painel de controle
    path(
        "paineldecontrole/",
        core_views.dashboard,
        name="dashboard",
    ),
    path(
        "paineldecontrole/solicitacoes/",
        movimentacao_views.solicitacao,
        name="solicitacoes",
    ),
    path(
        "paineldecontrole/solicitacoes/listartodas/<str:id>/",
        movimentacao_views.listar_solicitacoes,
        name="listar_solicitacoes",
    ),
    path(
        "paineldecontrole/solicitacoes/selecionar/<int:id>",
        movimentacao_views.solicitacao_mostra_view,
        name="solicitacoes_mostrar",
    ),
    path(
        "paineldecontrole/solicitacoes/finalizar/<int:id>",
        movimentacao_views.solciitacao_finaliza,
        name="solicitacoes_finalizar",
    ),
    path(
        "paineldecontrole/solicitacoes/bancodehoras/pendentes/",
        login_required(
            movimentacao_views.PainelDeControleSolicitacoesView.as_view(),
            login_url="login",
        ),
        name="dashboard_solicitacoes",
    ),
    path(
        "paineldecontrole/solicitacoes/baixas/pendentes/",
        login_required(
            movimentacao_views.PainelDeControleFolgasView.as_view(),
            login_url="login",
        ),
        name="dashboard_baixas",
    ),
    path(
        "paineldecontrole/solicitacoes/bancodehoras/",
        login_required(
            movimentacao_views.SolicitacaoBancoDeHorasView.as_view(),
            login_url="login",
        ),
        name="solicitacoes_banco_de_horas",
    ),
    path(
        "paineldecontrole/solicitacoes/baixas/",
        login_required(
            movimentacao_views.SolicitacaoBaixaView.as_view(),
            login_url="login",
        ),
        name="solicitacoes_baixas",
    ),
    # usuario
    path(
        "login/",
        usuario_views.LoginUsuarioView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        usuario_views.logout_usuario,
        name="logout",
    ),
    path(
        "usuario/cadastrar/",
        usuario_views.cadastrar_usuario,
        name="cadastrar_usuario",
    ),
    path(
        "usuario/seleciona/<str:id>",
        usuario_views.atualiza_usuario,
        name="usuario_atualiza",
    ),
    path(
        "usuario/atualiza/ativo/<int:id>",
        usuario_views.usuario_ativo,
        name="usuario_ativo",
    ),
    path(
        "usuario/atualiza/gerente/<int:id>",
        usuario_views.usuario_gerente,
        name="usuario_gerente",
    ),
    path(
        "usuario/atualiza/administrador/<int:id>",
        usuario_views.usuario_administrador,
        name="usuario_administrador",
    ),
]
