version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=bancodehoras.settings.dev
    volumes:
      - .:/code
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      # Database
      - POSTGRES_NAME=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_HOST}
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
